### ISSUE TITLE
set precision

### ISSUE THREAD

**Issue by jake5253** [rafaelfragosom/php-haversine-formula#4]
This works AMAZING! Thank you for making and sharing this little diddy. For my purposes, I have re-worked the code slightly to allow users to specify the precision of rounding the results, or default to 0 if it is not specified.  My project has some less than 1 mile away so I liked the precision to have 3 decimal places.  If you like, I encourage you to update the Distance class

```
class Distance {

	private static function calculate($fromLat, $fromLon, $toLat, $toLon, $precision = 0) {
		$earth_radius = 6371;

		$dLat = deg2rad($toLat - $fromLat);
		$dLon = deg2rad($toLon - $fromLon);
		
		$a = sin($dLat/2) * sin($dLat/2) + cos(deg2rad($fromLat)) * cos(deg2rad($toLat)) * sin($dLon/2) * sin($dLon/2);
		$c = 2 * asin(sqrt($a));
		$d = $earth_radius * $c;
		
		return round($d, $precision);
	}
  
  public static function toKilometers($fromLat, $fromLon, $toLat, $toLon, $precision = 0) {
	  return self::calculate($fromLat, $fromLon, $toLat, $toLon);
	}

  public static function toMiles($fromLat, $fromLon, $toLat, $toLon, $precision = 0) {
    $distance = self::calculate($fromLat, $fromLon, $toLat, $toLon, $precision);
	  return round($distance * 0.621371192, $precision);
	}

}
```

**Comment by damianopetrungaro** [comment]
You already wrote the implementation, add some tests and ask for a review 😄

**Comment by jake5253** [comment]
Not sure how to do that or I would have. 🤣

**Comment by damianopetrungaro** [comment]
There's a file in `tests` directory.

On that file, you should provide the assertion that the changes you introduced does not break the current implementation and are working as expected.

You may simply use DataProviders as [explained here](https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers)

**Comment by orafaelfragoso** [comment]
Feel free to send a PR, that's a great suggestion.

**Comment by andreshg112** [comment]
I just installed the package and I can't see the $precision variable.
![image](https://user-images.githubusercontent.com/15859884/49311312-d16f0180-f4ae-11e8-9b85-2b8248899f0b.png)

**Comment by thisischrisj** [comment]
+1
